#!/usr/bin/env bash
# Bootstrap one account and keep the bootstrap's own state in the bucket it creates.
#   first run : local state -> apply -> migrate state into S3
#   later runs: init straight against S3
# Usage: ./scripts/bootstrap.sh <dev|qa|prod>   (AWS credentials in env/profile)
set -euo pipefail

ENVIRONMENT="${1:?usage: bootstrap.sh <dev|qa|prod>}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/bootstrap"
REGION="${AWS_REGION:-us-east-1}"
TF="${TF:-terraform}"
AWS="${AWS:-aws}"
export AWS_REGION="$REGION" AWS_DEFAULT_REGION="$REGION"

ACCOUNT_ID="$("$AWS" sts get-caller-identity --query Account --output text)"
BUCKET="acme-tfstate-${ACCOUNT_ID}-${REGION}"

VARS=(-var-file="${ENVIRONMENT}.tfvars" -var "aws_account_id=${ACCOUNT_ID}" -var "region=${REGION}")
[ -n "${BUDGET_EMAIL:-}" ] && VARS+=(-var "budget_email=${BUDGET_EMAIL}")

write_backend() {
  cat > "$DIR/backend.tf" <<HCL
# Generated by scripts/bootstrap.sh - do not edit.
terraform {
  backend "s3" {
    key          = "bootstrap/terraform.tfstate"
    encrypt      = true
    kms_key_id   = "alias/terraform-state"
    use_lockfile = true
  }
}
HCL
}
BACKEND_CFG=(-backend-config="bucket=${BUCKET}" -backend-config="region=${REGION}")

if "$AWS" s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1 && [ -s "$DIR/terraform.tfstate" ]; then
  echo "State bucket exists but bootstrap state is still local - migrating it to S3."
  write_backend
  "$TF" -chdir="$DIR" init -input=false -migrate-state -force-copy "${BACKEND_CFG[@]}"
  rm -f "$DIR/terraform.tfstate" "$DIR/terraform.tfstate.backup"
  "$TF" -chdir="$DIR" apply -input=false -auto-approve "${VARS[@]}"
elif "$AWS" s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1; then
  echo "State bucket exists - using remote state."
  write_backend
  "$TF" -chdir="$DIR" init -input=false -reconfigure "${BACKEND_CFG[@]}"
  "$TF" -chdir="$DIR" apply -input=false -auto-approve "${VARS[@]}"
else
  echo "First run - applying with local state, then migrating it to S3."
  rm -f "$DIR/backend.tf"
  "$TF" -chdir="$DIR" init -input=false
  "$TF" -chdir="$DIR" apply -input=false -auto-approve "${VARS[@]}"
  write_backend
  "$TF" -chdir="$DIR" init -input=false -migrate-state -force-copy "${BACKEND_CFG[@]}"
  rm -f "$DIR/terraform.tfstate" "$DIR/terraform.tfstate.backup"
fi

echo
"$TF" -chdir="$DIR" output
